### ISSUE TITLE
`GFX.Light` block

### ISSUE THREAD

**Issue by sinkingsugar** [fragcolor-xyz/chainblocks#140]
* Should contribute the GFX.Context `_lightCount`, which is used by shaders.
* Should contribute to GLTF `_numLights` as well
* Should take a `Float3` as world position
* Should have classic game light parameters (Spot, Point, etc) and related parameters

Simple forward for now - figure out later future render complexities like implementing clustered rendering etc ( We need to discuss and spec before doing anything towards that direction )

**Comment by guusw** [comment]
Closing for now. Creating new task based on new graphics system.
