### ISSUE TITLE
Version Cargo.lock for rust projects

### ISSUE THREAD

**Issue by guusw** [fragcolor-xyz/chainblocks#173]
As mentioned by @Kryptos-FR : https://github.com/fragcolor-xyz/chainblocks/pull/162#discussion_r815948011

https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html#cargotoml-vs-cargolock
The above describes how the cargo lock files should be used.

Since we mostly produce binaries (dll/staticlib/exe) we should version the rust lock files to make builds more reproducible

**Comment by Kryptos-FR** [comment]
As an added benefit, it will make the [rust-cache](https://github.com/Swatinem/rust-cache) action more useful.

**Comment by sinkingsugar** [comment]
Not 100% sure it's multi-platform but should be ok.
