### ISSUE TITLE
ParseInt can only parse 32-bit numbers

### ISSUE THREAD

**Issue by Kryptos-FR** [fragcolor-xyz/chainblocks#182]
Looks like `(ParseInt)` is limited to 32-bit integers while our `int` type is supposed to be 64-bit.

```clj
"4294967295" (ParseInt) (Log) ;; ok
"4294967296" (ParseInt) (Log) ;; Block activation error, failed block: ParseInt, error: stoul
```

I guess we need to use `std::stoull` instead of `std::stoul`.

**Comment by guusw** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Whole-Team-623c70cfcdeee40011bd03e3/issues/fragcolor-xyz/chainblocks/182?planning-poker) with ZenHub @Kryptos-FR
