### ISSUE TITLE
Enhancement - Clean up block documentation code samples

### ISSUE THREAD

**Issue by satendrapalsingh** [fragcolor-xyz/chainblocks#229]
**Enhancement**
Remove the boilerplate `chain/loop` and `node` statements from the sample code of blocks that don't use UI (since the CICD script already wraps sample code scripts within `chain/loop` and `node` statements):
- [x] [ForEach](https://docs.fragcolor.xyz/blocks/General/ForEach/)
- [x] [Log](https://docs.fragcolor.xyz/blocks/General/Log/)
- [x] [Match](https://docs.fragcolor.xyz/blocks/General/Match/)
- [x] [Msg](https://docs.fragcolor.xyz/blocks/General/Msg/)
- [x] [Sub](https://docs.fragcolor.xyz/blocks/General/Sub/)
- [x] [Slice](https://docs.fragcolor.xyz/blocks/General/Slice/)
- [x] [Take](https://docs.fragcolor.xyz/blocks/General/Take/)
- [x] [RTake](https://docs.fragcolor.xyz/blocks/General/RTake/)

**Additional Context**
For reference, see the sample codes for blocks [Assoc](https://docs.fragcolor.xyz/blocks/General/Assoc/), [Add](https://docs.fragcolor.xyz/blocks/Math/Add/), and [Multiply](https://docs.fragcolor.xyz/blocks/Math/Multiply/).

**Comment by Kryptos-FR** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Whole-Team-623c70cfcdeee40011bd03e3/issues/fragcolor-xyz/chainblocks/229?planning-poker) with ZenHub @satendrapalsingh
